apiVersion: v1
kind: Service
metadata:
  name: mysql-service-1
  namespace: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  clusterIP: None
  selector:
    app: mysql
